---
- name: Connecting to Leaf
  hosts: ceos01
  connection: local
  gather_facts: false

  tasks:

    - name: Correct Interfaces
      arista.eos.eos_interfaces:
        config:
         - name: Ethernet1
           enabled: false
