---
- 
  name: Configure RHEL to join AD
  hosts: webservers
  gather_facts: true
  become: true

  vars_files:
    - windows_auth
  vars:
    domain:
    admin_username: ansibleadmin
    admin_password:
    packages:
      - samba-common-tools
      - realmd
      - oddjob
      - oddjob-mkhomedir
      - sssd
      - adcli
      - krb5-workstation
      - httpd

  tasks:

   - name: Install required packages
     ansible.builtin.yum:
       name: "{{ packages }}"
       state: present
        
   - name: Verify installation
     ansible.builtin.shell: |
       for package in {{ packages | join(' ') }}; do
         rpm -q $package || echo "$package not installed";
       done
     register: verify_packages

   - name: Debug package installation status
     ansible.builtin.debug:
       var: verify_packages.stdout_lines
        
   - name: Resolve DNS server hostname to IP
     set_fact:
      domain_controller: windows."{{ domain }}"

   - name: name
     debug:
      msg: "{{ domain_controller }}"

  
   - name: Resolve DNS server hostname to IP
     set_fact:
      dns_server_ip: "{{ lookup('dig', domain_controller) }}"

   - name: name
     debug:
      msg: "{{ dns_server_ip }}"

      #### RHEL Tasks 

   - name: Add DNS from AD to /etc/resolv
     lineinfile:
       path: /etc/resolv.conf
       regexp: '^# Generated by NetworkManager'
       line: |
         source {{ domain }}
         nameserver {{ dns_server_ip }}
       insertafter: '^# Generated by NetworkManager'

   - name: Bind to AD with realm
     block:
       - name: Join system
         ansible.builtin.command: /bin/bash -c "echo {{ admin_password }} | realm join --user={{ admin_username }} {{ domain }}"
         register: join_output

       - name: Display success message
         ansible.builtin.debug:
          msg: "Join successful!"
         when: join_output.rc == 0

       - name: Display error message
         ansible.builtin.debug:
          msg: "Join failed or already joined"
         when: join_output.rc != 0
   
