---
- 
  name: Create Organizational Units and Groups
  hosts: domain_controllers
  gather_facts: true

  vars:
   org_unit: 
   group_name:

  vars_files:
    - users

  tasks:

   - name: Create Organizational Unit
     microsoft.ad.ou:
      name: "{{ org_unit }}"
      state: present
      protect_from_deletion: true

   - name: Get DC details
     set_fact:
      domain_name: "{{ ansible_interfaces[0].dns_domain }}"

   - name: Remove trailing dot
     set_fact:
      domain_cleaned: "{{ domain_name | regex_replace('\\.$', '') }}"

   - name: Split domain and reformat as DC=value
     set_fact:
      formatted_domain: "{{ domain_cleaned.split('.') | map('regex_replace', '^', 'DC=') | join(', ') }}"

   - name: Create OU Path
     set_fact:
       ou_path: "OU={{ org_unit }},{{ formatted_domain }}"

   - name: Create a group in an OU
     microsoft.ad.group:
      identity: "{{ group_name }}"
      scope: global
      path: "{{ ou_path }}"
      state: present

   - name: Create users for lab
     microsoft.ad.user:
      identity: "{{ item.key }}"
      password: "{{ user_password }}"
      firstname: "{{ item.value.firstname }}"
      surname: "{{ item.value.surname }}"
      state: present
      groups:
       set:
        - "{{ group_name }}"
        - Domain Users
     loop: "{{ users_list | dict2items }}"

   - name: Create Ansible Admin
     microsoft.ad.user:
      identity: "{{ admin_user }}"
      password: "{{ admin_password }}"
      firstname: "Ansible AD"
      surname: "Administrator"
      state: present
      groups:
       set:
        - Domain Admins
        - Domain Users
  
