---
- name: Install software using Chocolatey
  hosts: windows
  
  tasks:
    - name: Ensure Chocolatey is installed
      win_chocolatey:
        name: chocolatey
        state: present

    - name: Install multiple packages sequentially
      win_chocolatey:
       name: '{{ item }}'
       state: present
      loop:
        - procexp
        - putty
        - windirstat
        - mysql
        - 7zip
        - git
        - notepadplusplus
        - python

    - name: Check python version
      ansible.windows.win_command: python --version
      register: check_python_version

    - name: Show python version
      ansible.builtin.debug:
       msg: Python Version is {{ check_python_version.stdout_lines[0] }}


